default_platform(:ios)

platform :ios do
  desc "Build and upload iOS App to App Store Connect"
  lane :release do
    key_path = File.expand_path("~/.appstoreconnect/private_keys/AuthKey_9T2974ST9M.p8")

    api_key = app_store_connect_api_key(
      key_id: "9T2974ST9M",
      issuer_id: "c8f0f943-872c-4153-b89a-86fb7cc78b8f",
      key_filepath: key_path
    )

    build_app(
      project: "ios/App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "GenYoga.ipa",
      clean: true,
      export_options: "./exportOptions.plist"
    )

    upload_to_app_store(
      api_key: api_key,
      ipa: "./build/GenYoga.ipa",
      skip_metadata: true,
      skip_screenshots: true,
      reject_build_waiting_for_review: false,
      distribute_external: false
    )
  end
end
