begin;

-- Version 6.9 introduces expiring class packs and turns the former monthly
-- pass into an unlimited membership. Every purchased pack keeps its own
-- expiry so overlapping purchases are consumed in earliest-expiry order.
-- Special classes are an independent class category (`taller`), not a flag on
-- a regular yoga class. The legacy flag remains only to migrate older rows.
alter table public.clases
  add column if not exists es_especial boolean not null default false;

comment on column public.clases.es_especial
  is 'Legacy compatibility mirror. Special classes are identified authoritatively by tipo_clase = taller.';

alter table public.tipos_clases
  add column if not exists categoria text not null default 'yoga';

alter table public.tipos_clases
  drop constraint if exists tipos_clases_categoria_check;
alter table public.tipos_clases
  add constraint tipos_clases_categoria_check
  check (categoria in ('yoga', 'taller'));

update public.clases
   set tipo_clase = 'taller'
 where coalesce(es_especial, false)
   and lower(trim(coalesce(tipo_clase, ''))) = 'yoga';

update public.clases
   set es_especial = lower(trim(coalesce(tipo_clase, ''))) = 'taller';

insert into public.tipos_clases (
  nombre, duracion_predeterminada, color, icono, activo, orden, categoria
)
select
  'Clase especial / Taller', 120, '#B45C47', 'ph-star-four', true,
  coalesce((select max(orden) from public.tipos_clases), 0) + 1,
  'taller'
where not exists (
  select 1 from public.tipos_clases where categoria = 'taller'
);

alter table public.reservas_yoga
  add column if not exists class_pack_id bigint,
  add column if not exists beneficio_invitado_de uuid references public.profiles(id) on delete set null;

alter table public.stripe_purchases
  drop constraint if exists stripe_purchases_purchase_type_check;
alter table public.stripe_purchases
  add constraint stripe_purchases_purchase_type_check check (
    purchase_type in (
      'clase_suelta',
      'pack_4',
      'pack_6',
      'pack_10',
      'bono_ilimitado',
      'bono_mensual'
    )
  );

alter table public.stripe_purchases
  add column if not exists membership_month date;
alter table public.stripe_purchases
  drop constraint if exists stripe_purchases_membership_month_check;
alter table public.stripe_purchases
  add constraint stripe_purchases_membership_month_check check (
    (purchase_type = 'bono_ilimitado' and (
      (membership_month is not null
        and membership_month = date_trunc('month', membership_month)::date)
      or (membership_month is null and subscription_id is not null)
    ))
    or (purchase_type <> 'bono_ilimitado' and membership_month is null)
  );

create table if not exists public.class_credit_packs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  checkout_session_id text unique references public.stripe_purchases(checkout_session_id) on delete set null,
  pack_type text not null check (
    pack_type in ('clase_suelta', 'pack_4', 'pack_6', 'pack_10')
  ),
  credits_total integer not null check (credits_total > 0),
  credits_remaining integer not null check (
    credits_remaining >= 0 and credits_remaining <= credits_total
  ),
  purchased_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint class_credit_packs_valid_period_check check (expires_at > purchased_at)
);

alter table public.class_credit_packs
  drop constraint if exists class_credit_packs_pack_type_check;
alter table public.class_credit_packs
  add constraint class_credit_packs_pack_type_check check (
    pack_type in ('clase_suelta', 'pack_4', 'pack_6', 'pack_10')
  );

alter table public.reservas_yoga
  drop constraint if exists reservas_yoga_class_pack_id_fkey;
alter table public.reservas_yoga
  add constraint reservas_yoga_class_pack_id_fkey
  foreign key (class_pack_id) references public.class_credit_packs(id) on delete restrict;

create index if not exists class_credit_packs_user_expiry_idx
  on public.class_credit_packs (user_id, expires_at, id)
  where credits_remaining > 0;

create index if not exists reservas_yoga_pack_idx
  on public.reservas_yoga (class_pack_id)
  where class_pack_id is not null;

create table if not exists public.unlimited_membership_periods (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  checkout_session_id text not null unique
    references public.stripe_purchases(checkout_session_id) on delete restrict,
  membership_month date not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  purchased_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint unlimited_membership_periods_one_month_per_user
    unique (user_id, membership_month),
  constraint unlimited_membership_periods_month_start_check check (
    membership_month = date_trunc('month', membership_month)::date
  ),
  constraint unlimited_membership_periods_valid_period_check check (ends_at > starts_at)
);

create index if not exists unlimited_membership_periods_user_dates_idx
  on public.unlimited_membership_periods (user_id, starts_at, ends_at);

create table if not exists public.unlimited_guest_passes (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references public.profiles(id) on delete cascade,
  guest_user_id uuid not null references public.profiles(id) on delete cascade,
  class_id bigint not null references public.clases(id) on delete restrict,
  reservation_id bigint not null unique references public.reservas_yoga(id) on delete cascade,
  guest_name text not null,
  guest_email text,
  membership_period_start timestamptz not null,
  membership_period_end timestamptz not null,
  created_at timestamptz not null default now(),
  constraint unlimited_guest_passes_one_per_period unique (
    owner_user_id,
    membership_period_start
  ),
  constraint unlimited_guest_passes_valid_period_check check (
    membership_period_end > membership_period_start
  )
);

create table if not exists public.unlimited_consultation_discounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  service text not null check (service in ('psicologia', 'nutricion')),
  discount_percent integer not null default 30 check (discount_percent = 30),
  membership_period_start timestamptz not null,
  membership_period_end timestamptz not null,
  redeemed_at timestamptz not null default now(),
  redeemed_by uuid references public.profiles(id) on delete set null,
  constraint unlimited_consultation_discount_valid_period_check check (
    membership_period_end > membership_period_start
  )
);

alter table public.class_credit_packs enable row level security;
alter table public.unlimited_membership_periods enable row level security;
alter table public.unlimited_guest_passes enable row level security;
alter table public.unlimited_consultation_discounts enable row level security;

drop policy if exists class_credit_packs_select_own on public.class_credit_packs;
create policy class_credit_packs_select_own
  on public.class_credit_packs for select to authenticated
  using (user_id = auth.uid());

drop policy if exists unlimited_membership_periods_select_own
  on public.unlimited_membership_periods;
create policy unlimited_membership_periods_select_own
  on public.unlimited_membership_periods for select to authenticated
  using (user_id = auth.uid());

drop policy if exists unlimited_guest_passes_select_own on public.unlimited_guest_passes;
create policy unlimited_guest_passes_select_own
  on public.unlimited_guest_passes for select to authenticated
  using (owner_user_id = auth.uid());

drop policy if exists unlimited_consultation_discounts_select_own
  on public.unlimited_consultation_discounts;
create policy unlimited_consultation_discounts_select_own
  on public.unlimited_consultation_discounts for select to authenticated
  using (user_id = auth.uid());

revoke all on table public.class_credit_packs from public, anon, authenticated;
revoke all on table public.unlimited_membership_periods from public, anon, authenticated;
revoke all on table public.unlimited_guest_passes from public, anon, authenticated;
revoke all on table public.unlimited_consultation_discounts from public, anon, authenticated;
grant select on table public.class_credit_packs to authenticated;
grant select on table public.unlimited_membership_periods to authenticated;
grant select on table public.unlimited_guest_passes to authenticated;
grant select on table public.unlimited_consultation_discounts to authenticated;
grant select, insert, update, delete on table public.class_credit_packs to service_role;
grant select, insert, update, delete on table public.unlimited_membership_periods to service_role;
grant select, insert, update, delete on table public.unlimited_guest_passes to service_role;
grant select, insert, update, delete on table public.unlimited_consultation_discounts to service_role;

-- Fulfil every allowed Stripe purchase exactly once. A single class and every
-- pack become independent 60-day credit buckets. The new unlimited pass is a
-- one-off purchase for a selected Madrid calendar month; the old recurring
-- subscription path remains only for existing subscriptions.
drop function if exists public.stripe_fulfill_checkout(
  text, text, bigint, text, uuid, boolean, text, text, text, text, text,
  bigint, text, text, timestamptz, timestamptz, text, boolean, boolean
);

create or replace function public.stripe_fulfill_checkout(
  p_event_id text,
  p_event_type text,
  p_event_created bigint,
  p_checkout_session_id text,
  p_user_id uuid,
  p_is_guest boolean,
  p_purchase_type text,
  p_price_id text,
  p_payment_intent_id text,
  p_subscription_id text,
  p_customer_id text,
  p_amount_total bigint,
  p_currency text,
  p_payment_status text,
  p_membership_month text,
  p_period_start timestamptz,
  p_period_end timestamptz,
  p_subscription_status text,
  p_cancel_at_period_end boolean,
  p_livemode boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_inserted integer;
  v_profile_updated integer := 0;
  v_existing public.stripe_purchases%rowtype;
  v_pack_credits integer;
  v_purchased_at timestamptz;
  v_account_deletion_pending boolean;
  v_membership_month date;
  v_membership_start timestamptz;
  v_membership_end timestamptz;
  v_current_month date;
begin
  if p_livemode is distinct from true then
    raise exception 'Only LIVE Stripe events are accepted' using errcode = '22023';
  end if;
  if nullif(trim(p_event_id), '') is null
    or nullif(trim(p_checkout_session_id), '') is null
    or nullif(trim(p_price_id), '') is null
    or p_event_type is distinct from 'checkout.session.completed'
    or p_event_created is null or p_event_created <= 0 then
    raise exception 'Missing Stripe identifiers' using errcode = '22023';
  end if;
  if p_payment_status is distinct from 'paid' or lower(p_currency) is distinct from 'eur' then
    raise exception 'Checkout is not a paid EUR session' using errcode = '22023';
  end if;

  v_pack_credits := case p_purchase_type
    when 'clase_suelta' then 1
    when 'pack_4' then 4
    when 'pack_6' then 6
    when 'pack_10' then 10
    else null
  end;

  if p_purchase_type = 'bono_ilimitado' then
    if nullif(trim(coalesce(p_membership_month, '')), '') is null
      or trim(p_membership_month) !~ '^\d{4}-(0[1-9]|1[0-2])$' then
      raise exception 'Unlimited checkout lacks a valid calendar month'
        using errcode = '22023';
    end if;
    v_membership_month := (trim(p_membership_month) || '-01')::date;
    v_current_month := date_trunc('month', timezone('Europe/Madrid', now()))::date;
    if v_membership_month < v_current_month
      or v_membership_month > (v_current_month + interval '11 months')::date then
      raise exception 'Unlimited calendar month is outside the allowed purchase window'
        using errcode = '22023';
    end if;
    v_membership_start := v_membership_month::timestamp at time zone 'Europe/Madrid';
    v_membership_end := (v_membership_month + interval '1 month')::timestamp
      at time zone 'Europe/Madrid';
  elsif nullif(trim(coalesce(p_membership_month, '')), '') is not null then
    raise exception 'Purchase type does not accept a calendar month' using errcode = '22023';
  end if;

  if p_purchase_type = 'clase_suelta' and p_amount_total is distinct from 1500 then
    raise exception 'Invalid single-class amount' using errcode = '22023';
  elsif p_purchase_type = 'pack_4' and p_amount_total is distinct from 5000 then
    raise exception 'Invalid four-class pack amount' using errcode = '22023';
  elsif p_purchase_type = 'pack_6' and p_amount_total is distinct from 6500 then
    raise exception 'Invalid six-class pack amount' using errcode = '22023';
  elsif p_purchase_type = 'pack_10' and p_amount_total is distinct from 9500 then
    raise exception 'Invalid ten-class pack amount' using errcode = '22023';
  elsif p_purchase_type in ('bono_ilimitado', 'bono_mensual')
    and p_amount_total is distinct from 9000 then
    raise exception 'Invalid unlimited-membership amount' using errcode = '22023';
  elsif p_purchase_type is null or p_purchase_type not in (
    'clase_suelta', 'pack_4', 'pack_6', 'pack_10',
    'bono_ilimitado', 'bono_mensual'
  ) then
    raise exception 'Unsupported purchase type' using errcode = '22023';
  end if;

  if p_is_guest is null then
    raise exception 'Missing guest purchase flag' using errcode = '22023';
  elsif p_is_guest and (p_user_id is not null or p_purchase_type <> 'clase_suelta') then
    raise exception 'Invalid guest purchase' using errcode = '22023';
  elsif not p_is_guest and p_user_id is null then
    raise exception 'Authenticated purchase has no user' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('gen_yoga_checkout:' || p_checkout_session_id, 0)
  );

  if not p_is_guest then
    select coalesce(account_deletion_pending, false)
      into v_account_deletion_pending
      from public.profiles
     where id = p_user_id
     for update;
    if not found then
      raise exception 'Profile not found for Stripe fulfillment' using errcode = 'P0002';
    end if;
    if v_account_deletion_pending then
      raise exception 'account deletion pending; entitlement update rejected' using errcode = '55000';
    end if;
  end if;

  insert into public.stripe_webhook_events (
    event_id, event_type, livemode, checkout_session_id, object_id
  ) values (
    p_event_id, p_event_type, true, p_checkout_session_id,
    coalesce(p_subscription_id, p_payment_intent_id, p_checkout_session_id)
  ) on conflict (event_id) do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then
    return jsonb_build_object('processed', false, 'reason', 'duplicate_event');
  end if;

  select * into v_existing
    from public.stripe_purchases
   where checkout_session_id = p_checkout_session_id
   for update;

  if found then
    if v_existing.is_guest <> p_is_guest
      or v_existing.user_id is distinct from p_user_id
      or v_existing.purchase_type <> p_purchase_type
      or v_existing.price_id <> p_price_id
      or v_existing.amount_total <> p_amount_total
      or v_existing.currency <> lower(p_currency)
      or v_existing.payment_status <> 'paid'
      or v_existing.membership_month is distinct from v_membership_month
      or (
        v_existing.payment_intent_id is not null and p_payment_intent_id is not null
        and v_existing.payment_intent_id <> p_payment_intent_id
      )
      or (
        v_existing.subscription_id is not null and p_subscription_id is not null
        and v_existing.subscription_id <> p_subscription_id
      )
      or (
        v_existing.customer_id is not null and p_customer_id is not null
        and v_existing.customer_id <> p_customer_id
      ) then
      raise exception 'Checkout session conflicts with an existing purchase' using errcode = '23514';
    end if;

    update public.stripe_purchases
       set stripe_event_id = coalesce(stripe_event_id, p_event_id),
           payment_intent_id = coalesce(payment_intent_id, p_payment_intent_id),
           subscription_id = coalesce(subscription_id, p_subscription_id),
           customer_id = coalesce(customer_id, p_customer_id),
           membership_month = coalesce(membership_month, v_membership_month),
           updated_at = now()
     where checkout_session_id = p_checkout_session_id;
    return jsonb_build_object('processed', false, 'reason', 'session_already_fulfilled');
  end if;

  if not p_is_guest and p_customer_id is not null then
    insert into public.stripe_customers (user_id, customer_id)
    values (p_user_id, p_customer_id)
    on conflict (user_id) do update
      set customer_id = excluded.customer_id, updated_at = now();
  end if;

  insert into public.stripe_purchases (
    checkout_session_id, stripe_event_id, user_id, is_guest, purchase_type,
    price_id, payment_intent_id, subscription_id, customer_id,
    amount_total, currency, payment_status, membership_month
  ) values (
    p_checkout_session_id, p_event_id, p_user_id, p_is_guest, p_purchase_type,
    p_price_id, p_payment_intent_id, p_subscription_id, p_customer_id,
    p_amount_total, lower(p_currency), p_payment_status, v_membership_month
  );

  if p_is_guest then
    return jsonb_build_object('processed', true, 'guest', true);
  end if;

  if v_pack_credits is not null then
    v_purchased_at := to_timestamp(p_event_created);
    insert into public.class_credit_packs (
      user_id, checkout_session_id, pack_type, credits_total,
      credits_remaining, purchased_at, expires_at
    ) values (
      p_user_id, p_checkout_session_id, p_purchase_type, v_pack_credits,
      v_pack_credits, v_purchased_at, v_purchased_at + interval '60 days'
    );
    update public.profiles
       set stripe_customer_id = coalesce(p_customer_id, stripe_customer_id)
     where id = p_user_id;
    get diagnostics v_profile_updated = row_count;
  elsif p_purchase_type = 'bono_ilimitado' then
    v_purchased_at := to_timestamp(p_event_created);
    insert into public.unlimited_membership_periods (
      user_id, checkout_session_id, membership_month,
      starts_at, ends_at, purchased_at
    ) values (
      p_user_id, p_checkout_session_id, v_membership_month,
      v_membership_start, v_membership_end, v_purchased_at
    );
    update public.profiles
       set stripe_customer_id = coalesce(p_customer_id, stripe_customer_id)
     where id = p_user_id;
    get diagnostics v_profile_updated = row_count;
  else
    if nullif(trim(p_subscription_id), '') is null
      or nullif(trim(p_customer_id), '') is null
      or nullif(trim(p_subscription_status), '') is null
      or p_period_start is null or p_period_end is null
      or p_period_end <= p_period_start then
      raise exception 'Unlimited checkout lacks a valid subscription period' using errcode = '22023';
    end if;

    insert into public.stripe_subscriptions (
      subscription_id, user_id, customer_id, price_id, status,
      current_period_start, current_period_end, cancel_at_period_end,
      last_event_created
    ) values (
      p_subscription_id, p_user_id, p_customer_id, p_price_id, p_subscription_status,
      p_period_start, p_period_end, coalesce(p_cancel_at_period_end, false),
      p_event_created
    )
    on conflict (subscription_id) do update
      set user_id = excluded.user_id,
          customer_id = excluded.customer_id,
          price_id = excluded.price_id,
          status = excluded.status,
          current_period_start = excluded.current_period_start,
          current_period_end = excluded.current_period_end,
          cancel_at_period_end = excluded.cancel_at_period_end,
          last_event_created = excluded.last_event_created,
          updated_at = now()
      where public.stripe_subscriptions.last_event_created <= excluded.last_event_created;

    update public.profiles
       set bono_mensual_activo = p_subscription_status in ('active', 'trialing'),
           bono_mensual_inicio = p_period_start,
           bono_mensual_fin = p_period_end,
           stripe_customer_id = coalesce(p_customer_id, stripe_customer_id),
           stripe_subscription_id = p_subscription_id,
           stripe_subscription_status = p_subscription_status,
           stripe_current_period_start = p_period_start,
           stripe_current_period_end = p_period_end,
           stripe_cancel_at_period_end = coalesce(p_cancel_at_period_end, false),
           stripe_subscription_event_created = p_event_created
     where id = p_user_id
       and coalesce(stripe_subscription_event_created, 0) <= p_event_created;
    get diagnostics v_profile_updated = row_count;
  end if;

  if v_profile_updated <> 1 and not exists (
    select 1 from public.profiles where id = p_user_id
  ) then
    raise exception 'Profile not found for Stripe fulfillment' using errcode = 'P0002';
  end if;

  return jsonb_build_object('processed', true, 'guest', false);
end;
$$;

-- Server-authoritative booking logic. Unlimited memberships have no weekly or
-- monthly cap for regular classes and one special class per calendar month.
create or replace function public.reservar_con_bono(
  p_clase_id bigint,
  p_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_role text;
  v_actor_email text;
  v_actor_is_staff boolean;
  v_target_role text;
  v_target_id uuid := p_user_id;
  v_legacy_credits integer;
  v_unlimited_active boolean;
  v_membership_start timestamptz;
  v_membership_end timestamptz;
  v_natural_membership_start timestamptz;
  v_natural_membership_end timestamptz;
  v_capacity integer;
  v_starts_at timestamptz;
  v_class_type text;
  v_class_active boolean;
  v_is_special boolean;
  v_professor_id public.clases.profesor_id%type;
  v_occupied integer;
  v_booking_limit_hours integer := 12;
  v_use_unlimited boolean := false;
  v_pack_id bigint;
  v_special_count integer := 0;
begin
  if v_actor_id is null then
    raise exception 'Debes iniciar sesión para reservar.' using errcode = '42501';
  end if;
  if p_clase_id is null or p_clase_id <= 0 or v_target_id is null then
    raise exception 'La solicitud de reserva no es válida.' using errcode = '22023';
  end if;

  select lower(trim(coalesce(rol, ''))), lower(nullif(trim(email), ''))
    into v_actor_role, v_actor_email
    from public.profiles where id = v_actor_id;
  if not found then
    raise exception 'No se encontró el perfil que realiza la reserva.' using errcode = 'P0002';
  end if;
  v_actor_is_staff := v_actor_role in ('admin', 'profesor', 'trabajador', 'profesional');
  if v_target_id <> v_actor_id and not v_actor_is_staff then
    raise exception 'No puedes reservar una clase para otra persona.' using errcode = '42501';
  end if;

  select coalesce(capacidad_max, 0), fecha_inicio,
         lower(trim(coalesce(tipo_clase, ''))), coalesce(activa, true),
         profesor_id
    into v_capacity, v_starts_at, v_class_type, v_class_active,
         v_professor_id
    from public.clases where id = p_clase_id for update;
  if not found or v_class_type not in ('yoga', 'taller') or not v_class_active then
    raise exception 'La clase especificada no está disponible.' using errcode = 'P0002';
  end if;
  v_is_special := v_class_type = 'taller';
  if v_starts_at is null then
    raise exception 'La clase no tiene una hora de inicio válida.' using errcode = '22023';
  end if;
  if v_capacity <= 0 then
    raise exception 'La clase no tiene plazas disponibles.' using errcode = 'P0001';
  end if;
  if v_target_id <> v_actor_id and v_actor_role <> 'admin'
    and not exists (
      select 1 from public.profesionales
       where id = v_professor_id
         and lower(nullif(trim(email), '')) = v_actor_email
    ) then
    raise exception 'Solo puedes gestionar reservas de tus propias clases.' using errcode = '42501';
  end if;

  begin
    select case when trim(coalesce(valor, '')) ~ '^[0-9]{1,3}$'
      then least(168, greatest(0, trim(valor)::integer)) else 12 end
      into v_booking_limit_hours
      from public.configuracion where clave = 'horas_limite_reserva' limit 1;
  exception when invalid_text_representation or numeric_value_out_of_range then
    v_booking_limit_hours := 12;
  end;
  v_booking_limit_hours := coalesce(v_booking_limit_hours, 12);
  if not v_actor_is_staff
    and v_starts_at <= now() + make_interval(hours => v_booking_limit_hours) then
    raise exception 'Las reservas cierran % h antes del inicio. Para esta clase ya ha pasado el plazo.',
      v_booking_limit_hours using errcode = 'P0001';
  end if;

  if exists (
    select 1 from public.reservas_yoga
     where clase_id = p_clase_id and user_id = v_target_id and estado = 'confirmada'
  ) then
    raise exception 'Ya tienes una reserva confirmada para esta clase.' using errcode = '23505';
  end if;
  select count(*)::integer into v_occupied
    from public.reservas_yoga
   where clase_id = p_clase_id and estado = 'confirmada';
  if v_occupied >= v_capacity then
    raise exception 'La clase está completa.' using errcode = 'P0001';
  end if;

  select lower(trim(coalesce(rol, ''))), coalesce(bonos, 0),
         coalesce(bono_mensual_activo, false), bono_mensual_inicio, bono_mensual_fin
    into v_target_role, v_legacy_credits, v_unlimited_active,
         v_membership_start, v_membership_end
    from public.profiles where id = v_target_id for update;
  if not found then
    raise exception 'No se encontró el perfil del alumno.' using errcode = 'P0002';
  end if;
  if v_target_role in ('admin', 'profesor', 'trabajador', 'profesional') then
    raise exception 'Solo los alumnos pueden reservar clases.' using errcode = '42501';
  end if;

  select starts_at, ends_at
    into v_natural_membership_start, v_natural_membership_end
    from public.unlimited_membership_periods
   where user_id = v_target_id
     and starts_at <= v_starts_at
     and ends_at > v_starts_at
   order by starts_at desc
   limit 1
   for share;
  if found then
    v_unlimited_active := true;
    v_membership_start := v_natural_membership_start;
    v_membership_end := v_natural_membership_end;
  end if;

  if v_unlimited_active
    and v_membership_start is not null and v_membership_end is not null
    and v_starts_at >= v_membership_start and v_starts_at < v_membership_end then
    if v_is_special then
      select count(*)::integer into v_special_count
        from public.reservas_yoga r
        join public.clases c on c.id = r.clase_id
       where r.user_id = v_target_id
         and r.estado = 'confirmada'
         and coalesce(r.usado_bono_mensual, false)
         and lower(trim(coalesce(c.tipo_clase, ''))) = 'taller'
         and c.fecha_inicio >= v_membership_start
         and c.fecha_inicio < v_membership_end;
      if v_special_count >= 1 then
        raise exception 'Ya has utilizado la clase especial incluida en este mes natural.'
          using errcode = 'P0001';
      end if;
    end if;
    v_use_unlimited := true;
  end if;

  if not v_use_unlimited then
    if v_is_special then
      raise exception 'Las clases especiales requieren un Bono Ilimitado activo y disponibilidad mensual.'
        using errcode = 'P0001';
    end if;

    select id into v_pack_id
      from public.class_credit_packs
     where user_id = v_target_id
       and credits_remaining > 0
       and expires_at > now()
       and expires_at >= v_starts_at
     order by expires_at, purchased_at, id
     limit 1
     for update;

    if v_pack_id is not null then
      update public.class_credit_packs
         set credits_remaining = credits_remaining - 1,
             updated_at = now()
       where id = v_pack_id and credits_remaining > 0;
      if not found then
        raise exception 'El pack seleccionado ya no tiene clases disponibles.' using errcode = 'P0001';
      end if;
    else
      update public.profiles
         set bonos = coalesce(bonos, 0) - 1
       where id = v_target_id and coalesce(bonos, 0) >= 1;
      if not found then
        raise exception 'No tienes clases vigentes disponibles para esta fecha.' using errcode = 'P0001';
      end if;
    end if;
  end if;

  insert into public.reservas_yoga (
    clase_id, user_id, estado, usado_bono_mensual, bono_descontado, class_pack_id
  ) values (
    p_clase_id, v_target_id, 'confirmada', v_use_unlimited,
    not v_use_unlimited, v_pack_id
  );
end;
$$;

create or replace function public.cancelar_con_bono(
  p_reserva_id bigint
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_role text;
  v_actor_email text;
  v_actor_is_staff boolean;
  v_actor_is_admin boolean;
  v_target_id uuid;
  v_class_id bigint;
  v_starts_at timestamptz;
  v_class_type text;
  v_professor_id public.clases.profesor_id%type;
  v_credit_debited boolean;
  v_pack_id bigint;
  v_cancel_limit_hours integer := 24;
  v_allow_admin_override boolean := false;
begin
  if v_actor_id is null then
    raise exception 'Debes iniciar sesión para cancelar.' using errcode = '42501';
  end if;
  if p_reserva_id is null or p_reserva_id <= 0 then
    raise exception 'La solicitud de cancelación no es válida.' using errcode = '22023';
  end if;

  select lower(trim(coalesce(rol, ''))), lower(nullif(trim(email), ''))
    into v_actor_role, v_actor_email
    from public.profiles where id = v_actor_id;
  if not found then
    raise exception 'No se encontró el perfil que realiza la cancelación.' using errcode = 'P0002';
  end if;
  v_actor_is_staff := v_actor_role in ('admin', 'profesor', 'trabajador', 'profesional');
  v_actor_is_admin := v_actor_role = 'admin';

  select user_id, clase_id, coalesce(bono_descontado, false), class_pack_id
    into v_target_id, v_class_id, v_credit_debited, v_pack_id
    from public.reservas_yoga
   where id = p_reserva_id and estado = 'confirmada'
   for update;
  if not found then
    raise exception 'La reserva especificada no existe.' using errcode = 'P0002';
  end if;
  if v_target_id <> v_actor_id and not v_actor_is_staff then
    raise exception 'No puedes cancelar la reserva de otra persona.' using errcode = '42501';
  end if;

  select fecha_inicio, lower(trim(coalesce(tipo_clase, ''))), profesor_id
    into v_starts_at, v_class_type, v_professor_id
    from public.clases where id = v_class_id for update;
  if not found or v_class_type not in ('yoga', 'taller') then
    raise exception 'Esta reserva no corresponde a una clase reservable.' using errcode = 'P0002';
  end if;
  if v_target_id <> v_actor_id and not v_actor_is_admin
    and not exists (
      select 1 from public.profesionales
       where id = v_professor_id
         and lower(nullif(trim(email), '')) = v_actor_email
    ) then
    raise exception 'Solo puedes gestionar reservas de tus propias clases.' using errcode = '42501';
  end if;

  begin
    select case when trim(coalesce(valor, '')) ~ '^[0-9]{1,3}$'
      then least(168, greatest(0, trim(valor)::integer)) else 24 end
      into v_cancel_limit_hours
      from public.configuracion where clave = 'horas_limite_cancelacion' limit 1;
  exception when invalid_text_representation or numeric_value_out_of_range then
    v_cancel_limit_hours := 24;
  end;
  v_cancel_limit_hours := coalesce(v_cancel_limit_hours, 24);
  if v_actor_is_admin then
    select lower(trim(coalesce(valor, ''))) in ('true', '1', 'yes', 'on')
      into v_allow_admin_override
      from public.configuracion where clave = 'permitir_cancelacion_admin_siempre' limit 1;
    v_allow_admin_override := coalesce(v_allow_admin_override, false);
  end if;
  if not (v_actor_is_admin and v_allow_admin_override)
    and (v_starts_at is null or v_starts_at <= now() + make_interval(hours => v_cancel_limit_hours)) then
    raise exception 'Ya no puedes cancelar: faltan % h o menos para la clase. El bono reservado no se devuelve.',
      v_cancel_limit_hours using errcode = 'P0001';
  end if;

  delete from public.reservas_yoga where id = p_reserva_id;

  if v_credit_debited and v_pack_id is not null then
    update public.class_credit_packs
       set credits_remaining = least(credits_total, credits_remaining + 1),
           updated_at = now()
     where id = v_pack_id and user_id = v_target_id;
    if not found then
      raise exception 'No se encontró el pack al devolver la clase.' using errcode = 'P0002';
    end if;
  elsif v_credit_debited then
    update public.profiles set bonos = coalesce(bonos, 0) + 1 where id = v_target_id;
    if not found then
      raise exception 'No se encontró el perfil al devolver el bono.' using errcode = 'P0002';
    end if;
  end if;
end;
$$;

-- Service-role operation used by the authenticated Edge Function that creates
-- the temporary guest identity. It consumes one regular-class guest allowance
-- per purchased calendar month and shares the same capacity/deadline locks.
create or replace function public.reservar_invitado_ilimitado(
  p_owner_user_id uuid,
  p_guest_user_id uuid,
  p_clase_id bigint,
  p_guest_name text,
  p_guest_email text default null
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_membership_start timestamptz;
  v_membership_end timestamptz;
  v_membership_active boolean;
  v_natural_membership_start timestamptz;
  v_natural_membership_end timestamptz;
  v_owner_role text;
  v_guest_role text;
  v_class_start timestamptz;
  v_capacity integer;
  v_occupied integer;
  v_booking_limit_hours integer := 12;
  v_reservation_id bigint;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_owner_user_id is null or p_guest_user_id is null or p_clase_id is null
    or nullif(trim(coalesce(p_guest_name, '')), '') is null then
    raise exception 'invalid unlimited guest request' using errcode = '22023';
  end if;

  select lower(trim(coalesce(rol, ''))), coalesce(bono_mensual_activo, false),
         bono_mensual_inicio, bono_mensual_fin
    into v_owner_role, v_membership_active, v_membership_start, v_membership_end
    from public.profiles where id = p_owner_user_id for update;
  if not found or v_owner_role in ('admin', 'profesor', 'trabajador', 'profesional') then
    raise exception 'unlimited membership owner not found' using errcode = 'P0002';
  end if;
  select lower(trim(coalesce(rol, ''))) into v_guest_role
    from public.profiles where id = p_guest_user_id for update;
  if not found or v_guest_role <> 'cliente_temporal' then
    raise exception 'temporary guest profile not found' using errcode = 'P0002';
  end if;

  select fecha_inicio, coalesce(capacidad_max, 0)
    into v_class_start, v_capacity
    from public.clases
   where id = p_clase_id
     and lower(trim(coalesce(tipo_clase, ''))) = 'yoga'
     and coalesce(activa, true)
    for update;
  if not found then
    raise exception 'guest benefit only applies to regular yoga classes' using errcode = 'P0002';
  end if;

  select starts_at, ends_at
    into v_natural_membership_start, v_natural_membership_end
    from public.unlimited_membership_periods
   where user_id = p_owner_user_id
     and starts_at <= v_class_start
     and ends_at > v_class_start
   order by starts_at desc
   limit 1
   for share;
  if found then
    v_membership_active := true;
    v_membership_start := v_natural_membership_start;
    v_membership_end := v_natural_membership_end;
  end if;
  if not v_membership_active or v_membership_start is null or v_membership_end is null
    or v_class_start < v_membership_start or v_class_start >= v_membership_end then
    raise exception 'unlimited membership is not active for this class'
      using errcode = 'P0001';
  end if;
  if exists (
    select 1 from public.unlimited_guest_passes
     where owner_user_id = p_owner_user_id
       and membership_period_start = v_membership_start
  ) then
    raise exception 'monthly unlimited guest allowance already used' using errcode = 'P0001';
  end if;
  begin
    select case when trim(coalesce(valor, '')) ~ '^[0-9]{1,3}$'
      then least(168, greatest(0, trim(valor)::integer)) else 12 end
      into v_booking_limit_hours
      from public.configuracion where clave = 'horas_limite_reserva' limit 1;
  exception when invalid_text_representation or numeric_value_out_of_range then
    v_booking_limit_hours := 12;
  end;
  if v_class_start <= now() + make_interval(hours => coalesce(v_booking_limit_hours, 12)) then
    raise exception 'booking deadline has passed' using errcode = 'P0001';
  end if;

  select count(*)::integer into v_occupied
    from public.reservas_yoga where clase_id = p_clase_id and estado = 'confirmada';
  if v_capacity <= 0 or v_occupied >= v_capacity then
    raise exception 'class is full' using errcode = 'P0001';
  end if;
  if exists (
    select 1 from public.reservas_yoga
     where clase_id = p_clase_id and user_id = p_guest_user_id and estado = 'confirmada'
  ) then
    raise exception 'guest is already booked in this class' using errcode = '23505';
  end if;

  insert into public.reservas_yoga (
    clase_id, user_id, estado, usado_bono_mensual, bono_descontado,
    beneficio_invitado_de
  ) values (
    p_clase_id, p_guest_user_id, 'confirmada', true, false, p_owner_user_id
  ) returning id into v_reservation_id;

  insert into public.unlimited_guest_passes (
    owner_user_id, guest_user_id, class_id, reservation_id,
    guest_name, guest_email, membership_period_start, membership_period_end
  ) values (
    p_owner_user_id, p_guest_user_id, p_clase_id, v_reservation_id,
    trim(p_guest_name), nullif(lower(trim(coalesce(p_guest_email, ''))), ''),
    v_membership_start, v_membership_end
  );

  return v_reservation_id;
end;
$$;

-- The discount is intentionally recorded once per client (not once per
-- renewal): it is a 30% discount on their first nutrition OR psychology
-- consultation. Administration applies it when arranging that first visit.
create or replace function public.registrar_descuento_primera_consulta(
  p_user_id uuid,
  p_service text
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_actor_role text;
  v_membership_active boolean;
  v_membership_start timestamptz;
  v_membership_end timestamptz;
  v_natural_membership_start timestamptz;
  v_natural_membership_end timestamptz;
  v_discount_id bigint;
  v_profile_found boolean;
begin
  select lower(trim(coalesce(rol, ''))) into v_actor_role
    from public.profiles where id = auth.uid();
  if not found or v_actor_role <> 'admin' then
    raise exception 'only administrators may redeem consultation discounts' using errcode = '42501';
  end if;
  if p_user_id is null or p_service not in ('psicologia', 'nutricion') then
    raise exception 'invalid consultation discount request' using errcode = '22023';
  end if;

  select coalesce(bono_mensual_activo, false), bono_mensual_inicio, bono_mensual_fin
    into v_membership_active, v_membership_start, v_membership_end
    from public.profiles where id = p_user_id for update;
  v_profile_found := found;
  select starts_at, ends_at
    into v_natural_membership_start, v_natural_membership_end
    from public.unlimited_membership_periods
   where user_id = p_user_id
     and starts_at <= now()
     and ends_at > now()
   order by starts_at desc
   limit 1
   for share;
  if found then
    v_membership_active := true;
    v_membership_start := v_natural_membership_start;
    v_membership_end := v_natural_membership_end;
  end if;
  if not v_profile_found or not v_membership_active or v_membership_start is null
    or v_membership_end is null or now() < v_membership_start or now() >= v_membership_end then
    raise exception 'client has no active unlimited membership' using errcode = 'P0001';
  end if;

  insert into public.unlimited_consultation_discounts (
    user_id, service, membership_period_start, membership_period_end, redeemed_by
  ) values (
    p_user_id, p_service, v_membership_start, v_membership_end, auth.uid()
  ) returning id into v_discount_id;
  return v_discount_id;
exception when unique_violation then
  raise exception 'first-consultation discount has already been used' using errcode = '23505';
end;
$$;

revoke all on function public.stripe_fulfill_checkout(
  text, text, bigint, text, uuid, boolean, text, text, text, text, text,
  bigint, text, text, text, timestamptz, timestamptz, text, boolean, boolean
) from public, anon, authenticated;
grant execute on function public.stripe_fulfill_checkout(
  text, text, bigint, text, uuid, boolean, text, text, text, text, text,
  bigint, text, text, text, timestamptz, timestamptz, text, boolean, boolean
) to service_role;

revoke all on function public.reservar_con_bono(bigint, uuid) from public, anon;
revoke all on function public.cancelar_con_bono(bigint) from public, anon;
grant execute on function public.reservar_con_bono(bigint, uuid) to authenticated;
grant execute on function public.cancelar_con_bono(bigint) to authenticated;

revoke all on function public.reservar_invitado_ilimitado(uuid, uuid, bigint, text, text)
  from public, anon, authenticated;
grant execute on function public.reservar_invitado_ilimitado(uuid, uuid, bigint, text, text)
  to service_role;

revoke all on function public.registrar_descuento_primera_consulta(uuid, text)
  from public, anon;
grant execute on function public.registrar_descuento_primera_consulta(uuid, text)
  to authenticated;

comment on function public.reservar_con_bono(bigint, uuid)
  is 'Books regular classes using a selected natural-month unlimited pass, earliest-expiry 60-day credit pack, or legacy credit; special classes use that calendar month allowance.';
comment on function public.cancelar_con_bono(bigint)
  is 'Cancels a yoga booking and restores the exact pack or legacy credit originally consumed.';
comment on function public.reservar_invitado_ilimitado(uuid, uuid, bigint, text, text)
  is 'Service-only atomic redemption of one regular-class guest benefit per purchased unlimited calendar month.';
comment on function public.registrar_descuento_primera_consulta(uuid, text)
  is 'Admin-only redemption of the one-time 30 percent first psychology or nutrition consultation discount.';

commit;
